/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreinamentosRouteImport } from './routes/treinamentos'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as RhRouteImport } from './routes/rh'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as MaquinasRouteImport } from './routes/maquinas'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GestaoRouteImport } from './routes/gestao'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as EpiRouteImport } from './routes/epi'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as DenunciasRouteImport } from './routes/denuncias'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ComunicadosRouteImport } from './routes/comunicados'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as IndexRouteImport } from './routes/index'

const TreinamentosRoute = TreinamentosRouteImport.update({
  id: '/treinamentos',
  path: '/treinamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const RhRoute = RhRouteImport.update({
  id: '/rh',
  path: '/rh',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const MaquinasRoute = MaquinasRouteImport.update({
  id: '/maquinas',
  path: '/maquinas',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoRoute = GestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const EpiRoute = EpiRouteImport.update({
  id: '/epi',
  path: '/epi',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const DenunciasRoute = DenunciasRouteImport.update({
  id: '/denuncias',
  path: '/denuncias',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunicadosRoute = ComunicadosRouteImport.update({
  id: '/comunicados',
  path: '/comunicados',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/comunicados': typeof ComunicadosRoute
  '/dashboard': typeof DashboardRoute
  '/denuncias': typeof DenunciasRoute
  '/documentos': typeof DocumentosRoute
  '/epi': typeof EpiRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/gestao': typeof GestaoRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/maquinas': typeof MaquinasRoute
  '/pedidos': typeof PedidosRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/rh': typeof RhRoute
  '/sobre': typeof SobreRoute
  '/suporte': typeof SuporteRoute
  '/treinamentos': typeof TreinamentosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/comunicados': typeof ComunicadosRoute
  '/dashboard': typeof DashboardRoute
  '/denuncias': typeof DenunciasRoute
  '/documentos': typeof DocumentosRoute
  '/epi': typeof EpiRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/gestao': typeof GestaoRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/maquinas': typeof MaquinasRoute
  '/pedidos': typeof PedidosRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/rh': typeof RhRoute
  '/sobre': typeof SobreRoute
  '/suporte': typeof SuporteRoute
  '/treinamentos': typeof TreinamentosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/comunicados': typeof ComunicadosRoute
  '/dashboard': typeof DashboardRoute
  '/denuncias': typeof DenunciasRoute
  '/documentos': typeof DocumentosRoute
  '/epi': typeof EpiRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/gestao': typeof GestaoRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/maquinas': typeof MaquinasRoute
  '/pedidos': typeof PedidosRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/rh': typeof RhRoute
  '/sobre': typeof SobreRoute
  '/suporte': typeof SuporteRoute
  '/treinamentos': typeof TreinamentosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/comunicados'
    | '/dashboard'
    | '/denuncias'
    | '/documentos'
    | '/epi'
    | '/esqueci-senha'
    | '/gestao'
    | '/login'
    | '/mapa'
    | '/maquinas'
    | '/pedidos'
    | '/redefinir-senha'
    | '/rh'
    | '/sobre'
    | '/suporte'
    | '/treinamentos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/comunicados'
    | '/dashboard'
    | '/denuncias'
    | '/documentos'
    | '/epi'
    | '/esqueci-senha'
    | '/gestao'
    | '/login'
    | '/mapa'
    | '/maquinas'
    | '/pedidos'
    | '/redefinir-senha'
    | '/rh'
    | '/sobre'
    | '/suporte'
    | '/treinamentos'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/comunicados'
    | '/dashboard'
    | '/denuncias'
    | '/documentos'
    | '/epi'
    | '/esqueci-senha'
    | '/gestao'
    | '/login'
    | '/mapa'
    | '/maquinas'
    | '/pedidos'
    | '/redefinir-senha'
    | '/rh'
    | '/sobre'
    | '/suporte'
    | '/treinamentos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  ComunicadosRoute: typeof ComunicadosRoute
  DashboardRoute: typeof DashboardRoute
  DenunciasRoute: typeof DenunciasRoute
  DocumentosRoute: typeof DocumentosRoute
  EpiRoute: typeof EpiRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  GestaoRoute: typeof GestaoRoute
  LoginRoute: typeof LoginRoute
  MapaRoute: typeof MapaRoute
  MaquinasRoute: typeof MaquinasRoute
  PedidosRoute: typeof PedidosRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  RhRoute: typeof RhRoute
  SobreRoute: typeof SobreRoute
  SuporteRoute: typeof SuporteRoute
  TreinamentosRoute: typeof TreinamentosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/treinamentos': {
      id: '/treinamentos'
      path: '/treinamentos'
      fullPath: '/treinamentos'
      preLoaderRoute: typeof TreinamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rh': {
      id: '/rh'
      path: '/rh'
      fullPath: '/rh'
      preLoaderRoute: typeof RhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maquinas': {
      id: '/maquinas'
      path: '/maquinas'
      fullPath: '/maquinas'
      preLoaderRoute: typeof MaquinasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao': {
      id: '/gestao'
      path: '/gestao'
      fullPath: '/gestao'
      preLoaderRoute: typeof GestaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epi': {
      id: '/epi'
      path: '/epi'
      fullPath: '/epi'
      preLoaderRoute: typeof EpiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/denuncias': {
      id: '/denuncias'
      path: '/denuncias'
      fullPath: '/denuncias'
      preLoaderRoute: typeof DenunciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunicados': {
      id: '/comunicados'
      path: '/comunicados'
      fullPath: '/comunicados'
      preLoaderRoute: typeof ComunicadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  ComunicadosRoute: ComunicadosRoute,
  DashboardRoute: DashboardRoute,
  DenunciasRoute: DenunciasRoute,
  DocumentosRoute: DocumentosRoute,
  EpiRoute: EpiRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  GestaoRoute: GestaoRoute,
  LoginRoute: LoginRoute,
  MapaRoute: MapaRoute,
  MaquinasRoute: MaquinasRoute,
  PedidosRoute: PedidosRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  RhRoute: RhRoute,
  SobreRoute: SobreRoute,
  SuporteRoute: SuporteRoute,
  TreinamentosRoute: TreinamentosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
