/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as MaquinasRouteImport } from './routes/maquinas'
import { Route as EpiRouteImport } from './routes/epi'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as DenunciasRouteImport } from './routes/denuncias'
import { Route as IndexRouteImport } from './routes/index'

const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const MaquinasRoute = MaquinasRouteImport.update({
  id: '/maquinas',
  path: '/maquinas',
  getParentRoute: () => rootRouteImport,
} as any)
const EpiRoute = EpiRouteImport.update({
  id: '/epi',
  path: '/epi',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const DenunciasRoute = DenunciasRouteImport.update({
  id: '/denuncias',
  path: '/denuncias',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/denuncias': typeof DenunciasRoute
  '/documentos': typeof DocumentosRoute
  '/epi': typeof EpiRoute
  '/maquinas': typeof MaquinasRoute
  '/pedidos': typeof PedidosRoute
  '/suporte': typeof SuporteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/denuncias': typeof DenunciasRoute
  '/documentos': typeof DocumentosRoute
  '/epi': typeof EpiRoute
  '/maquinas': typeof MaquinasRoute
  '/pedidos': typeof PedidosRoute
  '/suporte': typeof SuporteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/denuncias': typeof DenunciasRoute
  '/documentos': typeof DocumentosRoute
  '/epi': typeof EpiRoute
  '/maquinas': typeof MaquinasRoute
  '/pedidos': typeof PedidosRoute
  '/suporte': typeof SuporteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/denuncias'
    | '/documentos'
    | '/epi'
    | '/maquinas'
    | '/pedidos'
    | '/suporte'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/denuncias'
    | '/documentos'
    | '/epi'
    | '/maquinas'
    | '/pedidos'
    | '/suporte'
  id:
    | '__root__'
    | '/'
    | '/denuncias'
    | '/documentos'
    | '/epi'
    | '/maquinas'
    | '/pedidos'
    | '/suporte'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DenunciasRoute: typeof DenunciasRoute
  DocumentosRoute: typeof DocumentosRoute
  EpiRoute: typeof EpiRoute
  MaquinasRoute: typeof MaquinasRoute
  PedidosRoute: typeof PedidosRoute
  SuporteRoute: typeof SuporteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maquinas': {
      id: '/maquinas'
      path: '/maquinas'
      fullPath: '/maquinas'
      preLoaderRoute: typeof MaquinasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epi': {
      id: '/epi'
      path: '/epi'
      fullPath: '/epi'
      preLoaderRoute: typeof EpiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/denuncias': {
      id: '/denuncias'
      path: '/denuncias'
      fullPath: '/denuncias'
      preLoaderRoute: typeof DenunciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DenunciasRoute: DenunciasRoute,
  DocumentosRoute: DocumentosRoute,
  EpiRoute: EpiRoute,
  MaquinasRoute: MaquinasRoute,
  PedidosRoute: PedidosRoute,
  SuporteRoute: SuporteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
